-- ===========================================================================
-- Mapa de Ayuda — Limpieza de ubicaciones erroneas en PRODUCCION
-- Ejecuta este archivo en: Supabase > SQL Editor.
-- Borra 62 hospitales mal importados de OpenStreetMap
-- (fuera de Venezuela o con nombres genericos sin identidad).
-- ===========================================================================
delete from public.locations where id in (
    'distrito-capital-centro-de-atencion-ambulatoria',
    'distrito-capital-centro-de-medicina-fisica-y-rehabilitacion-ips',
    'distrito-capital-centro-de-salud-club-de-leones',
    'distrito-capital-centro-medico-bautista',
    'distrito-capital-centro-medico-la-costa',
    'distrito-capital-centro-medico-maitei',
    'distrito-capital-centro-nacional-de-control-de-adicciones',
    'distrito-capital-centro-nacional-de-prevencion-y-tratamiento-de-adicciones-cenptra',
    'distrito-capital-centro-oftalmologico',
    'distrito-capital-clinica-cetro-s-a',
    'distrito-capital-clinica-de-mastologia',
    'distrito-capital-clinica-de-mastologia-2',
    'distrito-capital-clinica-de-mastologia-3',
    'distrito-capital-clinica-del-ips-12-de-junio',
    'distrito-capital-clinica-ima',
    'distrito-capital-clinica-periferica-nanawa',
    'distrito-capital-complejo-hospital-de-la-policia-nacional-doctor-rigoberto-caballero',
    'distrito-capital-direccion-general-de-sanidad-policia-nacional-paraguay',
    'distrito-capital-electroneuro',
    'distrito-capital-fundacor',
    'distrito-capital-hospital-central-de-policia-rigoberto-caballero',
    'distrito-capital-hospital-central-del-instituto-de-prevision-social-paraguay',
    'distrito-capital-hospital-de-barrio-obrero',
    'distrito-capital-hospital-de-clinicas',
    'distrito-capital-hospital-de-loma-pyta',
    'distrito-capital-hospital-de-trauma-prof-dr-manuel-giagni',
    'distrito-capital-hospital-del-quemado',
    'distrito-capital-hospital-geriatrico',
    'distrito-capital-hospital-materno-infantil-san-pablo',
    'distrito-capital-hospital-materno-infantil-santisima-trinidad',
    'distrito-capital-hospital-neuropsquiatrico-de-asuncion',
    'distrito-capital-hospital-reina-sofia',
    'distrito-capital-hospital-san-lucas',
    'distrito-capital-hospital-san-martin',
    'distrito-capital-hospital-universitario-ntra-sra-de-la-asuncion',
    'distrito-capital-inat-instituto-nacional-de-ablacion-y-transplante',
    'distrito-capital-instituto-de-medicina-tropical',
    'distrito-capital-instituto-de-prevision-social-i-p-s',
    'distrito-capital-ipn',
    'distrito-capital-ips',
    'distrito-capital-medicis',
    'distrito-capital-predio-del-hospital-del-barrio-san-pablo',
    'distrito-capital-prof-dr-victor-canata',
    'distrito-capital-puesto-de-salud-virgen-de-fatima',
    'distrito-capital-samaritano',
    'distrito-capital-sanatorio-americano',
    'distrito-capital-sanatorio-italiano',
    'distrito-capital-sanatorio-migone',
    'distrito-capital-sanatorio-profesor-doctor-juan-max-boettner',
    'distrito-capital-sanatorio-san-lucas',
    'distrito-capital-sanatorio-san-lucas-2',
    'distrito-capital-sanatorio-san-marcos',
    'distrito-capital-sanatorio-santa-barbara',
    'distrito-capital-sanatorio-santa-barbara-2',
    'distrito-capital-santa-barbaba',
    'distrito-capital-santa-barbara',
    'distrito-capital-usf-san-alfonso',
    'la-guaira-modulo',
    'miranda-ambulatorio',
    'miranda-ambulatorio-2',
    'miranda-modulo',
    'miranda-modulo-2'
);
